// ==================== PUSTAKA TEKNIS PIPA PLASTIK ====================
const pustakaData = [
  // ===== HANDBOOK & MANUAL =====
  { id:'H01', title:'Handbook of Polyethylene Pipe (2nd Edition)', author:'Plastics Pipe Institute (PPI)', year:2008, cat:'handbook', material:'HDPE', tags:['design','installation','properties','fusion'], summary:'Panduan komprehensif pipa PE — mencakup material science, hydraulic design, butt/electrofusion, instalasi, rehabilitasi, dan marine applications. Referensi utama untuk engineer HDPE.', pages:620, access:'open', url:'https://plasticpipe.org/publications/' },
  { id:'H02', title:'PVC Pipe — Design and Installation (AWWA M23)', author:'American Water Works Association', year:2020, cat:'handbook', material:'PVC', tags:['design','installation','water supply'], summary:'Manual desain dan instalasi pipa PVC untuk sistem air minum. Mencakup pemilihan material, desain hidrolik, bedding, thrust restraint, dan pressure testing.', pages:284, access:'purchase', url:'https://www.awwa.org/Resources-Tools/Resource-Topics/Pipe' },
  { id:'H03', title:'PE Pipe — Design and Installation (AWWA M55)', author:'American Water Works Association', year:2020, cat:'handbook', material:'HDPE', tags:['design','installation','water supply','trenchless'], summary:'Manual AWWA untuk pipa PE dalam jaringan air minum. Termasuk HDD, pipe bursting, slip lining, dan marine/subaqueous installations.', pages:350, access:'purchase', url:'https://www.awwa.org/Resources-Tools/Resource-Topics/Pipe' },
  { id:'H04', title:'Uni-Bell PVC Pipe Handbook (5th Edition)', author:'Uni-Bell PVC Pipe Association', year:2012, cat:'handbook', material:'PVC', tags:['design','hydraulics','installation','testing'], summary:'Handbook PVC untuk pressure & gravity pipe. Mencakup hydraulic design, structural analysis, bedding factors, dan commissioning.', pages:466, access:'open', url:'https://uni-bell.org/resources/' },
  { id:'H05', title:'Engineering Properties of Polyethylene', author:'Plastics Pipe Institute (PPI)', year:2009, cat:'handbook', material:'HDPE', tags:['material properties','stress','creep','fatigue'], summary:'Properti teknis PE100/PE80 — tensile strength, creep modulus, stress relaxation, fatigue resistance, dan thermal properties.', pages:52, access:'open', url:'https://plasticpipe.org/publications/' },
  { id:'H06', title:'PP Piping Systems — Technical Manual', author:'Aquatherm GmbH / Georg Fischer', year:2022, cat:'handbook', material:'PPR', tags:['design','socket fusion','installation','hot water'], summary:'Manual teknis sistem perpipaan PP-R untuk air panas dan dingin. Parameter socket fusion, expansion loop, insulation, dan fire rating.', pages:180, access:'open', url:'https://www.aquatherm.de/en/downloads/' },
  { id:'H07', title:'Ductile Iron Pipe & PE Pipe — Comparison Guide', author:'DIPRA / PPI Joint Publication', year:2018, cat:'handbook', material:'General', tags:['comparison','material selection','lifecycle cost'], summary:'Perbandingan teknis dan ekonomis pipa ductile iron vs PE — covering installation, lifecycle, corrosion resistance, dan operating costs.', pages:44, access:'open', url:'https://plasticpipe.org/publications/' },
  { id:'H08', title:'PVC-O Pipes Technical Manual', author:'Molecor / TOM® PVC-O', year:2023, cat:'handbook', material:'PVC-O', tags:['design','installation','oriented PVC','high performance'], summary:'Manual teknis pipa PVC-O (oriented PVC). Properti mekanik superior, instalasi, dan keunggulan dibanding PVC-U dan PE.', pages:96, access:'open', url:'https://molecor.com/en/downloads' },

  // ===== TECHNICAL NOTES (PPI) =====
  { id:'TN01', title:'PPI TN-27: Frequently Asked Questions — PE Pipe', author:'Plastics Pipe Institute', year:2020, cat:'technical-note', material:'HDPE', tags:['FAQ','general','PE pipe basics'], summary:'Kumpulan FAQ pipa PE — mencakup material classification, pressure rating, chemical resistance, UV resistance, dan joining methods. Status: Archived, tersedia via PPI.', pages:28, access:'open', url:'https://plasticpipe.org/publications/' },
  { id:'TN02', title:'PPI TN-46: Field Hydrostatic Testing of HDPE Pipelines', author:'Plastics Pipe Institute', year:2019, cat:'technical-note', material:'HDPE', tags:['pressure test','commissioning','field testing'], summary:'Panduan uji hidrostatis lapangan pipa HDPE. Memperhitungkan sifat viskoelastis PE saat test — initial expansion, make-up water allowance.', pages:16, access:'open', url:'https://plasticpipe.org/publications/' },
  { id:'TN03', title:'PPI TN-38: Chemical Resistance of PE Piping Materials', author:'Plastics Pipe Institute', year:2021, cat:'technical-note', material:'HDPE', tags:['chemical resistance','compatibility','corrosion'], summary:'Daftar ketahanan kimia pipa PE terhadap 400+ senyawa kimia. Essential reference untuk aplikasi industri dan tambang.', pages:32, access:'open', url:'https://plasticpipe.org/publications/' },
  { id:'TN04', title:'PPI TN-42: Recommendations for Butt Fusion of PE Pipe', author:'Plastics Pipe Institute', year:2022, cat:'technical-note', material:'HDPE', tags:['butt fusion','welding','joining','quality'], summary:'Rekomendasi parameter butt fusion PE — heater temperature, fusion pressure, heating/cooling time, QC procedures. Status: Archived, superseded by ASTM F3190.', pages:20, access:'open', url:'https://plasticpipe.org/publications/' },
  { id:'TN05', title:'PPI TN-36: PE Pipe Joining Procedures for Municipal Applications', author:'Plastics Pipe Institute', year:2018, cat:'technical-note', material:'HDPE', tags:['joining','electrofusion','mechanical','municipal'], summary:'Prosedur penyambungan pipa PE untuk aplikasi air minum — butt fusion, electrofusion, mechanical coupling, dan flange adaptor.', pages:24, access:'open', url:'https://plasticpipe.org/publications/' },
  { id:'TN06', title:'PPI TN-7: Nature of Hydrostatic Stress Rupture Curves', author:'Plastics Pipe Institute', year:2015, cat:'technical-note', material:'General', tags:['stress rupture','long-term strength','HDB','MRS'], summary:'Penjelasan kurva stress rupture hidrostatik pipa termoplastik. Dasar penentuan HDB (ASTM) dan MRS (ISO) untuk desain tekanan.', pages:12, access:'open', url:'https://plasticpipe.org/publications/' },
  { id:'TN07', title:'PPI TN-16: Rate Process Method for Projecting HDB', author:'Plastics Pipe Institute', year:2016, cat:'technical-note', material:'General', tags:['HDB','regression','long-term','pressure rating'], summary:'Metode proyeksi Hydrostatic Design Basis menggunakan rate process (ASTM D2837). Fundamental untuk pressure rating pipa.', pages:18, access:'open', url:'https://plasticpipe.org/publications/' },
  { id:'TN08', title:'PPI TN-56: HDPE Pipe for Potable Water — Permeation Concerns', author:'Plastics Pipe Institute', year:2021, cat:'technical-note', material:'HDPE', tags:['permeation','contamination','potable water','safety'], summary:'Evaluasi risiko permeasi kontaminan melalui dinding pipa HDPE pada aplikasi air minum. Faktor keamanan dan rekomendasi.', pages:14, access:'open', url:'https://plasticpipe.org/publications/' },

  // ===== DESIGN GUIDES =====
  { id:'G01', title:'TEPPFA Guide to PE Pipe Installation', author:'The European Plastic Pipe and Fittings Association', year:2021, cat:'guide', material:'HDPE', tags:['installation','trenching','backfill','Europe'], summary:'Panduan instalasi pipa PE di Eropa — excavation, bedding, backfill, compaction, dan connection to other pipe materials.', pages:48, access:'open', url:'https://teppfa.eu/guides-manuals/' },
  { id:'G02', title:'WRc Guide to PE Pipe Systems — Design and Installation', author:'Water Research Centre (UK)', year:2018, cat:'guide', material:'HDPE', tags:['design','UK','water industry','installation'], summary:'Panduan Water Research Centre (UK) untuk desain dan instalasi sistem pipa PE. Referensi industri air Inggris.', pages:120, access:'purchase', url:'https://www.wrcgroup.com/' },
  { id:'G03', title:'IGEM/TD/3 Edition 5 — PE Pipe Systems for Gas Supply', author:'Institution of Gas Engineers & Managers', year:2018, cat:'guide', material:'HDPE', tags:['gas','distribution','UK','safety'], summary:'Standar dan panduan pipa PE untuk distribusi gas (UK). Mencakup design, construction, commissioning, dan maintenance.', pages:186, access:'purchase', url:'https://www.igem.org.uk/' },
  { id:'G04', title:'DVS Technical Codes for Welding Thermoplastics (Compendium)', author:'DVS — German Welding Society', year:2020, cat:'guide', material:'General', tags:['welding','fusion','DVS','German standards'], summary:'Kumpulan kode teknis DVS untuk pengelasan termoplastik — butt fusion, socket fusion, electrofusion, extrusion welding.', pages:240, access:'purchase', url:'https://www.dvs-media.eu/' },
  { id:'G05', title:'Aliaxis/GPS PE Pipe Systems — Technical Handbook', author:'Aliaxis UK (formerly GPS PE Pipe Systems)', year:2022, cat:'guide', material:'HDPE', tags:['technical','specifications','PE100','UK'], summary:'Manual teknis Aliaxis/GPS untuk pipa PE100 — meliputi pressure rating, chemical resistance, flow characteristics, dan jointing.', pages:88, access:'open', url:'https://www.aliaxis.co.uk/' },
  { id:'G06', title:'PIPA PVC Pipe Design & Installation Guide (Australia)', author:'Plastics Industry Pipe Association of Australia', year:2019, cat:'guide', material:'PVC', tags:['installation','Australia','PVC-U','PVC-O','trenchless'], summary:'Panduan instalasi pipa PVC dari PIPA Australia. Termasuk PVC-U, PVC-M, dan PVC-O untuk tekanan dan non-tekanan.', pages:72, access:'open', url:'https://www.pipa.com.au/' },
  { id:'G07', title:'Panduan Pemasangan Pipa HDPE untuk Jaringan Air Minum', author:'Kementerian PUPR RI', year:2017, cat:'guide', material:'HDPE', tags:['Indonesia','PUPR','air minum','instalasi'], summary:'Panduan teknis Kementerian PUPR untuk pemasangan pipa HDPE pada jaringan air minum di Indonesia.', pages:85, access:'open', url:'https://pfrdb.litbang.pu.go.id/' },
  { id:'G08', title:'Pedoman Teknis Pemasangan Meter Air dan Pipa PDAM', author:'PERPAMSI / Kementerian PUPR', year:2019, cat:'guide', material:'General', tags:['Indonesia','PDAM','water meter','service connection'], summary:'Pedoman teknis pemasangan meter air dan sambungan rumah PDAM. Mencakup pemilihan pipa, meter air, dan prosedur pemasangan.', pages:64, access:'open', url:'https://perpamsi.or.id/' },
  { id:'G09', title:'BPF Pipes Group — Specification Guide for PE Pipe & Fittings', author:'British Plastics Federation Pipes Group', year:2024, cat:'guide', material:'HDPE', tags:['UK','specifications','BS EN 12201','2024 update'], summary:'Panduan terbaru (2024) dari BPF untuk spesifikasi pipa dan fitting PE di UK — mencakup referensi BS EN 12201, BS 8588, WIS 4-32-08.', pages:32, access:'open', url:'https://www.bpfpipesgroup.com/' },

  // ===== JURNAL & PAPER =====
  { id:'J01', title:'Plastics Pipes XIX — Conference Proceedings', author:'Plastics Pipes Conference Association', year:2018, cat:'journal', material:'General', tags:['conference','research','innovation','global'], summary:'Prosiding konferensi internasional Plastics Pipes XIX. Paper riset terbaru: material development, trenchless, large diameter, recycling.', pages:800, access:'open', url:'https://plasticpipesconference.com/site/database' },
  { id:'J02', title:'Plastics Pipes XX — Conference Proceedings', author:'Plastics Pipes Conference Association', year:2021, cat:'journal', material:'General', tags:['conference','research','sustainability','digital'], summary:'Prosiding Plastics Pipes XX. Topik: sustainability, digital transformation, advanced materials, dan circular economy.', pages:750, access:'open', url:'https://plasticpipesconference.com/site/database' },
  { id:'J03', title:'Long-Term Performance of PE100 Pipe — 50 Year Extrapolation Study', author:'Beech, S.H. et al. (Exova)', year:2016, cat:'journal', material:'HDPE', tags:['long-term','stress rupture','PE100','50 year'], summary:'Studi ekstrapolasi performa 50 tahun pipa PE100 berdasarkan data stress rupture test. Bukti keandalan jangka panjang.', pages:12, access:'open', url:'https://www.pe100plus.com/' },
  { id:'J04', title:'Slow Crack Growth Resistance of PE100 and PE100-RC', author:'Frank, A. et al. (JKU Linz)', year:2019, cat:'journal', material:'HDPE', tags:['SCG','crack resistance','PE100-RC','FNCT'], summary:'Riset ketahanan perambatan retak lambat pada PE100 vs PE100-RC menggunakan FNCT (Full Notch Creep Test). Data kritis untuk pipa trenchless.', pages:10, access:'open', url:'https://www.pe100plus.com/' },
  { id:'J05', title:'Fatigue Life of PE Pipe Under Cyclic Pressure', author:'Krishnaswamy, R.K. (Dow Chemical)', year:2017, cat:'journal', material:'HDPE', tags:['fatigue','cyclic pressure','pump station','design life'], summary:'Analisis umur fatigue pipa PE akibat tekanan siklik (water hammer, pump cycling). Penting untuk desain near pump stations.', pages:14, access:'purchase', url:'https://doi.org/10.1016/j.polymdegradstab.2017.01.001' },
  { id:'J06', title:'Comparative Study: PVC-O vs HDPE for Water Networks', author:'Pipoyan, L. & Rubeiz, C.', year:2020, cat:'journal', material:'General', tags:['PVC-O','HDPE','comparison','water network','lifecycle'], summary:'Studi perbandingan PVC-O dan HDPE untuk jaringan distribusi air — hydraulics, installation cost, lifecycle cost analysis.', pages:16, access:'open', url:'https://molecor.com/en/downloads' },
  { id:'J07', title:'Effect of Welding Parameters on Butt Fusion Joint Quality', author:'Leskovics, K. et al.', year:2019, cat:'journal', material:'HDPE', tags:['butt fusion','quality','parameters','destructive test'], summary:'Analisis pengaruh parameter las (suhu, tekanan, waktu) terhadap kualitas sambungan butt fusion PE. Hasil uji tarik dan bend test.', pages:12, access:'purchase', url:'https://doi.org/10.1016/j.engfailanal.2019.04.023' },

  // ===== REGULASI & PANDUAN INDONESIA =====
  { id:'R01', title:'Permen PUPR No. 27/2016 — Penyelenggaraan SPAM', author:'Kementerian PUPR RI', year:2016, cat:'regulation', material:'General', tags:['Indonesia','SPAM','PUPR','air minum','regulasi'], summary:'Peraturan Menteri PUPR tentang Penyelenggaraan Sistem Penyediaan Air Minum. Dasar hukum penggunaan material pipa di Indonesia.', pages:120, access:'open', url:'https://jdih.pu.go.id/' },
  { id:'R02', title:'Permen ESDM No. 26/2018 — K3 Pertambangan Mineral dan Batubara', author:'Kementerian ESDM RI', year:2018, cat:'regulation', material:'General', tags:['Indonesia','tambang','K3','ESDM','dewatering'], summary:'Regulasi K3 pertambangan yang mencakup standar perpipaan dewatering dan slurry transport di area tambang.', pages:85, access:'open', url:'https://jdih.esdm.go.id/' },
  { id:'R03', title:'Perpres No. 16/2018 — Pengadaan Barang/Jasa Pemerintah (TKDN)', author:'Pemerintah RI', year:2018, cat:'regulation', material:'General', tags:['Indonesia','TKDN','pengadaan','local content'], summary:'Peraturan Presiden tentang Pengadaan Barang/Jasa termasuk ketentuan TKDN (Tingkat Komponen Dalam Negeri) untuk produk pipa.', pages:64, access:'open', url:'https://jdih.lkpp.go.id/' },
  { id:'R04', title:'SE Kementerian PUPR — Standar Material Pipa Air Minum', author:'Kementerian PUPR RI', year:2021, cat:'regulation', material:'General', tags:['Indonesia','PUPR','material','sertifikasi','SNI'], summary:'Surat Edaran tentang persyaratan standar material pipa untuk proyek air minum — termasuk kewajiban SNI dan sertifikasi.', pages:12, access:'open', url:'https://jdih.pu.go.id/' },
  { id:'R05', title:'Pedoman Perencanaan dan Pemasangan Jaringan Pipa Air Minum', author:'Ditjen Cipta Karya, Kementerian PUPR', year:2020, cat:'guide', material:'General', tags:['Indonesia','perencanaan','PDAM','jaringan'], summary:'Pedoman teknis perencanaan dan pemasangan jaringan distribusi air minum. Pemilihan material, dimensioning, dan layout jaringan.', pages:156, access:'open', url:'https://ciptakarya.pu.go.id/' },

  // ===== ONLINE RESOURCES & DATABASE =====
  { id:'D01', title:'PE100+ Association — Technical Library', author:'PE100+ Association', year:2024, cat:'database', material:'HDPE', tags:['database','PE100','research','case study','online'], summary:'Database online terlengkap tentang pipa PE100 — data teknis, case studies, 1000+ research papers dari Plastics Pipes Conference, dan guidance documents.', pages:0, access:'open', url:'https://www.pe100plus.com/' },
  { id:'D02', title:'PPI — Complete Technical Publications Library', author:'Plastics Pipe Institute', year:2024, cat:'database', material:'General', tags:['database','PPI','standards','technical notes','online'], summary:'Koleksi lengkap publikasi teknis PPI — Technical Notes, Technical Reports, dan Policies. Sumber utama referensi pipa plastik Amerika.', pages:0, access:'open', url:'https://plasticpipe.org/publications/' },
  { id:'D03', title:'Uni-Bell — Technical Resources and Publications', author:'Uni-Bell PVC Pipe Association', year:2024, cat:'database', material:'PVC', tags:['database','PVC','resources','online'], summary:'Koleksi referensi teknis PVC dari Uni-Bell — termasuk design manuals, reports, dan webinar recordings.', pages:0, access:'open', url:'https://uni-bell.org/resources/' },
  { id:'D04', title:'TEPPFA — European Plastic Pipe Technical Library', author:'TEPPFA', year:2024, cat:'database', material:'General', tags:['database','Europe','publications','sustainability','online'], summary:'Perpustakaan teknis asosiasi pipa plastik Eropa — position papers, LCA studies, installation guides, dan buried pipe design tool.', pages:0, access:'open', url:'https://teppfa.eu/guides-manuals/' },
  { id:'D05', title:'PPCA — Plastics Pipes Conference Paper Database', author:'Plastics Pipes Conference Association', year:2024, cat:'database', material:'General', tags:['database','conference','papers','1970-present','online'], summary:'Database 1000+ paper teknis dari konferensi Plastics Pipes sejak 1970. Searchable by topic, author, dan conference year.', pages:0, access:'open', url:'https://plasticpipesconference.com/site/database' },
];

// Category metadata
const pustakaCategoryMeta = {
  'handbook': { label:'Handbook & Manual', color:'#00bcd4', icon:'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></svg>' },
  'technical-note': { label:'Technical Note', color:'#ff6d00', icon:'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>' },
  'guide': { label:'Panduan Teknis', color:'#00e676', icon:'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>' },
  'journal': { label:'Jurnal & Paper', color:'#aa66ff', icon:'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>' },
  'regulation': { label:'Regulasi Indonesia', color:'#ff5252', icon:'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m16 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z"/><path d="m2 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z"/><path d="M7 21h10"/><path d="M12 3v18"/><path d="M3 7h2c2 0 5-1 7-2 2 1 5 2 7 2h2"/></svg>' },
  'database': { label:'Database Online', color:'#2196f3', icon:'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/></svg>' },
};

const pustakaMatColors = {
  'HDPE':'#00bcd4', 'PVC':'#7c4dff', 'PVC-O':'#ff6d00', 'PPR':'#00e676', 'General':'#78909c'
};
